#jwt.auth.app: gyhame;
jwt:
  token:
    secret_key: YW1lcnNvbmFuhijmmlugbuhnuhwerhwefsndfjdfbgifandidshgbweidknaklfbndsjabqiwfjnesofwandjerbgioewjfsdoknijyYmFuZ2xh
    expiration_time: 172800000
#  auth:
#    expires_in: 2535

#logging:
#  level:
#    root: DEBUG

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG